import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { Scenes } from "@/scenes";
import Typewriter from "@/components/typewriter";

export default function Home() {
  const [currentScene, setScene] = useState(Scenes[""]);

  const switchScene = (newScene: string): any => {
    setScene(Scenes[newScene]);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Typewriter text={currentScene.text}></Typewriter>
        <li className={styles.list}>
          {currentScene.choices.map((choice: any) => (
            <button
              className={styles.choice}
              key={choice.text}
              onClick={() => switchScene(choice.scene)}
            >
              {choice.text}
            </button>
          ))}
        </li>
      </main>
    </>
  );
}
